apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  REDIS_HOST: "{{ .Values.config.redisHost }}"
  SCHEDULER_TIME: "{{ .Values.config.schedulerTime }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.corsAllowedOrigins }}"
  AWS_REGION: "{{ .Values.config.awsRegion }}"
  S3_BUCKET_NAME: "{{ .Values.config.s3BucketName }}"
  S3_PRESIGNED_EXPIRATION: "{{ .Values.config.s3PresignedExpiration }}"
  JWT_ACCESS_EXP: "{{ .Values.config.jwtAccessExp }}"
  JWT_REFRESH_EXP: "{{ .Values.config.jwtRefreshExp }}"