apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api.mondcommunity.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mondcommunity-backend-svc
                port:
                  number: 80