apiVersion: v1
kind: Service
metadata:
  name: mondcommunity-backend-svc
spec:
  type: ClusterIP
  selector:
    app: mondcommunity
    tier: backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP