apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
  namespace: default
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: mondcommunity
      tier: backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s