replicaCount: 2

image:
  repository: 028210901650.dkr.ecr.ap-northeast-2.amazonaws.com/be-running/ecr
  tag: f369e5446ca24332800ebb97333b0ab382df9e30
  imagePullSecretName: ecr-secret

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "768Mi"

config:
  redisHost: "mondcommunity-redis-svc"
  schedulerTime: "10000"
  corsAllowedOrigins: "https://mondcommunity.store"
  awsRegion: "ap-northeast-2"
  s3BucketName: "running-community-images-028210901650-ap-northeast-2-an"
  s3PresignedExpiration: "10"
  jwtAccessExp: "1800"
  jwtRefreshExp: "1209600"