apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.4
    helm:
      values: |
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          useTestSchema: true

        deploymentMode: SingleBinary

        # --- 캐시 컴포넌트 전면 비활성화 (메모리 절약) ---
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false

        singleBinary:
          replicas: 1
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        test:
          enabled: false
        lokiCanary:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true